### ISSUE TITLE
I can't get picture uploaded by use LookupFileID func

### ISSUE THREAD

**Issue by bluedragonflyliu** [linxGnu/goseaweedfs#10]
after UploadFile(filepath, "", "") I get one fid and use this fid in LookupFileID,I can't get the picture through the fullUrl

if use seaweed direct  can upload file and can lookup the picture can get picture by browser as well,
but still can't  get picture through fid goseaweedfs client created

version v0.1.3

seaweed version 1.45

It seem error happen at line 151 resp, err = c.client.Post(url, mw.FormDataContentType(), r)

http://172.16.1.135:9333/4,0a8d1aa4d3?Content-Type=multipart%2Fform-data&ts=1540190469
&{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[0] Date:[Tue, 26 Nov 2019 08:05:50 GMT]] 0xc000126380 0 [] false false map[] 0xc00022a900 <nil>}

curl http://172.16.1.135:9333/dir/assign
curl -F file=@./qe.jpg http://172.16.1.131:8084/1,11899cc110

use http://172.16.1.131:8084/1,11899cc110 by browser is well

**Comment by linxGnu** [comment]
Thank you very much for the report @bluedragonflyliu Could you please show me the full code you use.

1. I believe that Download is Get method, which is specified in v0.1.3
2. `err = c.client.Post(url, mw.FormDataContentType(), r)` as you said, could you please give me fullstack trace? And this call should only for uploading, not downloading/get uploaded picture

**Comment by bluedragonflyliu** [comment]
It seem that upload not use weed master returned  value volume's url  use master url directly

**Comment by linxGnu** [comment]
Thank you very much @bluedragonflyliu I could simulate the issue right now. Seem my mistake for changes happened with seaweedfs new version.
I would fix the issue and let you know asap.

**Comment by linxGnu** [comment]
@bluedragonflyliu 

Please kindly find the fix in https://github.com/linxGnu/goseaweedfs/pull/11

Could you confirm that it works for you?

**Comment by bluedragonflyliu** [comment]
thank you very much, upload,replace(remov true) and delete work well.
