### ISSUE TITLE
Function name inconsistency

### ISSUE THREAD

**Issue by chikamim** [linxGnu/goseaweedfs#12]
Hi.
I found inconsistency(typo?) named functions in Filer client. ("Upload" and "UploadFile")

https://github.com/linxGnu/goseaweedfs/blob/4e832fba6905435b312338386d7415e0132463de/filer.go#L54
https://github.com/linxGnu/goseaweedfs/blob/4e832fba6905435b312338386d7415e0132463de/filer.go#L70

https://github.com/linxGnu/goseaweedfs/blob/4e832fba6905435b312338386d7415e0132463de/seaweed.go#L298
https://github.com/linxGnu/goseaweedfs/blob/4e832fba6905435b312338386d7415e0132463de/seaweed.go#L306

I hope these will be fixed!

**Comment by linxGnu** [comment]
Hello @chikamim Thank you very much for your report.
I fix the typo in https://github.com/linxGnu/goseaweedfs/pull/13
Will release the patch asap.

**Comment by linxGnu** [comment]
Released v0.1.5. Thank you very much @chikamim
