### ISSUE TITLE
Filer not support upload file compression

### ISSUE THREAD

**Issue by suriyaJaboon** [linxGnu/goseaweedfs#14]
- filer download file compression open error
- please add `application/x-gzip; charset=utf-8` or `application/gzip; charset=utf-8` if suffix `.tgz` `.gz` `.gzip`

**Comment by linxGnu** [comment]
@suriyaJaboon It's server duty to add header `Content-Encoding`, not the client for downloading case.
Could you please check it out on SeaweedFS side?

**Comment by suriyaJaboon** [comment]
Thank you
