### ISSUE TITLE
Can't download file with height or width

### ISSUE THREAD

**Issue by s-khaon** [linxGnu/goseaweedfs#16]
http(s)://host:port/1,01c49454679ed7?width=200&height=200

Download method don't build args to fileURL.

**Comment by linxGnu** [comment]
I am sorry due to personal matter that I could not handle issue on time.

Please let me check and feedback. Additionally, could you please let me know how which version of seaweedfs server you are using?

**Comment by s-khaon** [comment]
> I am sorry due to personal matter that I could not handle issue on time.
> 
> Please let me check and feedback. Additionally, could you please let me know how which version of seaweedfs server you are using? @s-khaon

I must have made a mistake before, now it works well.
