### ISSUE TITLE
need help about UploadFile with ttl

### ISSUE THREAD

**Issue by hjhsamuel** [linxGnu/goseaweedfs#18]
it's working when using the function `UploadFile` without ttl, but when i do like this `UploadFile(path, "", "5m")` ,i can only get the fileid but cannot find the uploaded file 

seaweedfs master service log:
![image](https://user-images.githubusercontent.com/20057029/200988666-067d6425-c4c6-4de2-8534-e418537f576a.png)
my seaweedfs master service using the default repliction 000, and has no filer service

i can upload file using `curl` command:
![image](https://user-images.githubusercontent.com/20057029/200990956-97dcd1a6-378d-44cd-917e-6cf0f60b8066.png)

could you give me some examples? Thanks a million

**Comment by hjhsamuel** [comment]
i got the question, `UploadFIle` would deliver the param `ts` by default, so i could only update the modification time everytime?

**Comment by linxGnu** [comment]
Hi, I will feedback to you tomorrow (likely). Will have to check the server api as well.

what is the version of seaweedfs you are using?

**Comment by hjhsamuel** [comment]
my seaweedfs version: 
`version 30GB 3.34 47db75a6 linux amd64`

now i update the modification time before upload file and it's working fine:
`os.Chtimes(path, time.Now(), time.Now())`

i would close the issue, and i also looking forward to your reply if you have some better solutions

**Comment by linxGnu** [comment]
@hjhsamuel I could not find abnormal issue at my side. 

According to your screen capture, it looks to me that there is some issue at server side: Volume id 1, which hold your file, was deleted.

Optionally, you can provide me more error logs from both server and client side for further investigation. Thank you
