### ISSUE TITLE
ttl have bug 

### ISSUE THREAD

**Issue by GeorgeWang1994** [linxGnu/goseaweedfs#9]
i also have a question。can filer add ttl ？

**Comment by linxGnu** [comment]
@GeorgeWang1994 I don't see TTL in wiki of seaweedfs. But I think `yes`, filer should support `ttl`

**Comment by linxGnu** [comment]
I would close this comment. Please kindly tell me if my answer is good fit your question. Thank you @GeorgeWang1994
